name: Welcome

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Welcome to LART Onboarding Demo! Thanks for opening your first issue."
          pr-message: "🚀 Welcome to LART Onboarding Demo! Please read our contributing guide (that we don't have)."
